#!/bin/sh -e



case "$1" in
    remove)
        # Old theme location
        update-alternatives --remove default.plymouth /lib/plymouth/themes/tmaxgooroom/tmaxgooroom.plymouth || true
        update-alternatives --remove text.plymouth /lib/plymouth/themes/tmaxgooroomt/tmaxgooroom.plymouth || true

        # Remove old alternative (plymouth-set-default-theme)
        update-alternatives --remove default.plymouth /usr/share/plymouth/themes/tmaxgooroom/tmaxgooroom.plymouth || true
        update-alternatives --remove text.plymouth /usr/share/plymouth/themes/tmaxgooroom/tmaxgooroom.plymouth || true
        ;;

    purge)
        ;;

    upgrade|failed-upgrade|disappear)
        ;;

    abort-install|abort-upgrade)
        ;;

    *)
        echo "$0 called with unknown argument \`$1'" 1>&2
        exit 1
        ;;
esac

exit 0
